#!/bin/sh

# Detect if running as root or not and set paths accordingly
if [ "$(id -u)" -eq 0 ]; then
    echo "Please do not run this script as root."
    REPO_LIST=/usr/.suprapack/repo.list
    CONFIG=/usr/.suprapack/user.conf
else
    REPO_LIST=$HOME/.local/.suprapack/repo.list
    CONFIG=$HOME/.local/.suprapack/user.conf
    mkdir -p $HOME/.config
    ln -sf $HOME/.local/.suprapack $HOME/.config/suprapack 2> /dev/null || true
fi

# Create user.conf if it doesn't exist
if [ ! -f "$CONFIG" ]; then
    mkdir -p "$(dirname "$CONFIG")"
    echo "is_cached:false" > "$CONFIG"
fi

# Set prefix in user.conf
if [ "$(id -u)" -eq 0 ]; then
    echo "prefix:/usr" > "$CONFIG"
else
    # 
    LOAD_STR='[ -f "$HOME/.suprapack_profile" ] && . "$HOME/.suprapack_profile"'
    
    # Load suprapack_profile in various shell configuration files if not already present
    TARGET_FILES="$HOME/.bashrc $HOME/.zshrc"

    for f in $TARGET_FILES; do
        if [ -f "$f" ]; then
            if ! grep -q ".suprapack_profile" "$f"; then
				echo "Loading suprapack_profile in $f"
                echo "" >> "$f"
                echo "# Added by suprapack installer" >> "$f"
                echo "$LOAD_STR" >> "$f"
                echo "Updated: $f"
            fi
        fi
    done
fi

# Update MIME database and desktop database
update-mime-database "$PREFIX/share/mime" 2>/dev/null || true
update-desktop-database "$PREFIX/share/applications" 2>/dev/null || true

# Set xdg-mime association for application/x-suprapack
if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default suprapack-installer.desktop application/x-suprapack
elif command -v gio >/dev/null 2>&1; then
    gio mime application/x-suprapack suprapack-installer.desktop
fi

# Regenerate suprapack profile
$PREFIX/bin/suprapack --regenerate_suprapack_profile
