#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
    SED_I="sed -i ''"
else
    SED_I="sed -i"
fi

if [ "$(id -u)" -eq 0 ]; then
    echo "Please do not run this script as root."
    mkdir -p /usr/.suprapack
    REPO_LIST=/usr/.suprapack/repo.list
else
    if [ -f "$HOME/.zshrc" ]; then
        if ! grep -q 'fpath+=($HOME/.local/share/zsh/site-functions)' "$HOME/.zshrc"; then
            $SED_I '1i\
fpath+=($HOME/.local/share/zsh/site-functions)' "$HOME/.zshrc"
        fi
    fi
    mkdir -p "$HOME/.local/.suprapack"
    REPO_LIST="$HOME/.local/.suprapack/repo.list"
fi

if [ -f "$REPO_LIST" ]; then
    echo "Updating repository URLs..."
    
    $SED_I "s|Cosmos https://gitlab.com/supraproject/suprastore_repository/-/raw/master/cosmos/|Cosmos https://pub-bdf6ee863f034a7c9317a95dd598f914.r2.dev/|g" "$REPO_LIST"
    
    $SED_I "s|Supravim https://gitlab.com/supraproject/suprastore_repository/-/raw/master/supravim/|Supravim https://pub-55fb6b54929c4e71a16bc01b43b593fb.r2.dev/|g" "$REPO_LIST"
else
    echo "Cosmos https://pub-bdf6ee863f034a7c9317a95dd598f914.r2.dev/" > "$REPO_LIST"
    echo "Supravim https://pub-55fb6b54929c4e71a16bc01b43b593fb.r2.dev/" >> "$REPO_LIST"
fi

if ! command -v suprapack >/dev/null 2>&1; then
    if command -v zenity >/dev/null 2>&1; then
        zenity --info --text='first installation of suprapack.\nfor best results, restart your session or use `source ~/.profile`. ' --title=Suprapack 2>/dev/null &
    fi
fi

true
