/* main.c generated by valac 0.56.13, the Vala compiler
 * generated from main.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <glib/gstdio.h>
#include <locale.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _main_unref0(var) ((var == NULL) ? NULL : (var = (main_unref (var), NULL)))
typedef struct _ParamSpecMain ParamSpecMain;

struct _Main {
	GTypeInstance parent_instance;
	volatile int ref_count;
	MainPrivate * priv;
};

struct _MainClass {
	GTypeClass parent_class;
	void (*finalize) (Main *self);
};

struct _ParamSpecMain {
	GParamSpec parent_instance;
};

VALA_EXTERN gchar* PREFIX;
gchar* PREFIX = NULL;
VALA_EXTERN gchar* LOCAL;
gchar* LOCAL = NULL;
VALA_EXTERN gchar* USERNAME;
gchar* USERNAME = NULL;
static gpointer main_parent_class = NULL;

VALA_EXTERN gpointer main_ref (gpointer instance);
VALA_EXTERN void main_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_main (const gchar* name,
                             const gchar* nick,
                             const gchar* blurb,
                             GType object_type,
                             GParamFlags flags);
VALA_EXTERN void value_set_main (GValue* value,
                     gpointer v_object);
VALA_EXTERN void value_take_main (GValue* value,
                      gpointer v_object);
VALA_EXTERN gpointer value_get_main (const GValue* value);
VALA_EXTERN GType main_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Main, main_unref)
VALA_EXTERN gboolean main_all_cmd (Main* self,
                       gchar** args,
                       gint args_length1);
VALA_EXTERN gboolean cmd_run (gchar** av,
                  gint av_length1);
VALA_EXTERN void print_error (const gchar* msg);
VALA_EXTERN Main* main_new (gchar** args,
                gint args_length1);
VALA_EXTERN Main* main_construct (GType object_type,
                      gchar** args,
                      gint args_length1);
static void main_main (gchar** args,
                gint args_length1);
static void main_finalize (Main * obj);
static GType main_get_type_once (void);

gboolean
main_all_cmd (Main* self,
              gchar** args,
              gint args_length1)
{
	gchar* av1 = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = args[1];
	_tmp1_ = g_utf8_strdown (_tmp0_, (gssize) -1);
	av1 = _tmp1_;
	if (g_strcmp0 (av1, "run") == 0) {
		result = cmd_run (args, (gint) args_length1);
		_g_free0 (av1);
		return result;
	}
	print_error ("La commande n'existe pas.");
}

Main*
main_construct (GType object_type,
                gchar** args,
                gint args_length1)
{
	Main* self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	const gchar* _tmp6_;
	self = (Main*) g_type_create_instance (object_type);
	_tmp0_ = g_get_user_name ();
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (USERNAME);
	USERNAME = _tmp1_;
	_tmp2_ = g_get_home_dir ();
	_tmp3_ = g_strconcat (_tmp2_, "/.local", NULL);
	_g_free0 (PREFIX);
	PREFIX = _tmp3_;
	_tmp4_ = g_get_home_dir ();
	_tmp5_ = g_strconcat (_tmp4_, "/suprapack", NULL);
	_g_free0 (LOCAL);
	LOCAL = _tmp5_;
	_tmp6_ = LOCAL;
	g_mkdir (_tmp6_, 0755);
	setlocale (LC_ALL, "");
	if (main_all_cmd (self, args, (gint) args_length1) == TRUE) {
		exit (0);
	}
	exit (1);
	return self;
}

Main*
main_new (gchar** args,
          gint args_length1)
{
	return main_construct (TYPE_MAIN, args, args_length1);
}

static void
main_main (gchar** args,
           gint args_length1)
{
	Main* _tmp0_;
	Main* _tmp1_;
	_tmp0_ = main_new (args, args_length1);
	_tmp1_ = _tmp0_;
	_main_unref0 (_tmp1_);
}

int
main (int argc,
      char ** argv)
{
	main_main (argv, argc);
	return 0;
}

static void
value_main_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_main_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		main_unref (value->data[0].v_pointer);
	}
}

static void
value_main_copy_value (const GValue* src_value,
                       GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_main_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_main_collect_value (GValue* value,
                          guint n_collect_values,
                          GTypeCValue* collect_values,
                          guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Main * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_main_lcopy_value (const GValue* value,
                        guint n_collect_values,
                        GTypeCValue* collect_values,
                        guint collect_flags)
{
	Main ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = main_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_main (const gchar* name,
                 const gchar* nick,
                 const gchar* blurb,
                 GType object_type,
                 GParamFlags flags)
{
	ParamSpecMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_main (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN), NULL);
	return value->data[0].v_pointer;
}

void
value_set_main (GValue* value,
                gpointer v_object)
{
	Main * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		main_unref (old);
	}
}

void
value_take_main (GValue* value,
                 gpointer v_object)
{
	Main * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		main_unref (old);
	}
}

static void
main_class_init (MainClass * klass,
                 gpointer klass_data)
{
	main_parent_class = g_type_class_peek_parent (klass);
	((MainClass *) klass)->finalize = main_finalize;
}

static void
main_instance_init (Main * self,
                    gpointer klass)
{
	self->ref_count = 1;
}

static void
main_finalize (Main * obj)
{
	Main * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
	g_signal_handlers_destroy (self);
}

static GType
main_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_main_init, value_main_free_value, value_main_copy_value, value_main_peek_pointer, "p", value_main_collect_value, "p", value_main_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType main_type_id;
	main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Main", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return main_type_id;
}

GType
main_get_type (void)
{
	static volatile gsize main_type_id__once = 0;
	if (g_once_init_enter (&main_type_id__once)) {
		GType main_type_id;
		main_type_id = main_get_type_once ();
		g_once_init_leave (&main_type_id__once, main_type_id);
	}
	return main_type_id__once;
}

gpointer
main_ref (gpointer instance)
{
	Main * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
main_unref (gpointer instance)
{
	Main * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

