/* Sync.c generated by valac 0.56.13, the Vala compiler
 * generated from Sync.vala, do not modify */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_SUPRA_LIST (supra_list_get_type ())
typedef struct _SupraList SupraList;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_REPO_INFO (repo_info_get_type ())
#define REPO_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REPO_INFO, RepoInfo))
#define REPO_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REPO_INFO, RepoInfoClass))
#define IS_REPO_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REPO_INFO))
#define IS_REPO_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REPO_INFO))
#define REPO_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REPO_INFO, RepoInfoClass))

typedef struct _RepoInfo RepoInfo;
typedef struct _RepoInfoClass RepoInfoClass;
typedef struct _RepoInfoPrivate RepoInfoPrivate;
typedef struct _ParamSpecRepoInfo ParamSpecRepoInfo;

struct _SupraList {
	const gchar* repo_name;
	gchar* name;
	gchar* version;
};

struct _RepoInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RepoInfoPrivate * priv;
	gchar* name;
	gchar* url;
};

struct _RepoInfoClass {
	GTypeClass parent_class;
	void (*finalize) (RepoInfo *self);
};

struct _RepoInfoPrivate {
	gchar* _list;
};

struct _ParamSpecRepoInfo {
	GParamSpec parent_instance;
};

static gint RepoInfo_private_offset;
static gpointer repo_info_parent_class = NULL;
VALA_EXTERN gchar* USERNAME;

VALA_EXTERN GType supra_list_get_type (void) G_GNUC_CONST ;
VALA_EXTERN SupraList* supra_list_dup (const SupraList* self);
VALA_EXTERN void supra_list_free (SupraList* self);
VALA_EXTERN void supra_list_copy (const SupraList* self,
                      SupraList* dest);
VALA_EXTERN void supra_list_destroy (SupraList* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (SupraList, supra_list_destroy)
VALA_EXTERN void supra_list_init (SupraList *self,
                      const gchar* repo_name,
                      const gchar* line);
VALA_EXTERN gpointer repo_info_ref (gpointer instance);
VALA_EXTERN void repo_info_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_repo_info (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
VALA_EXTERN void value_set_repo_info (GValue* value,
                          gpointer v_object);
VALA_EXTERN void value_take_repo_info (GValue* value,
                           gpointer v_object);
VALA_EXTERN gpointer value_get_repo_info (const GValue* value);
VALA_EXTERN GType repo_info_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (RepoInfo, repo_info_unref)
VALA_EXTERN RepoInfo* repo_info_new (const gchar* name,
                         const gchar* url);
VALA_EXTERN RepoInfo* repo_info_construct (GType object_type,
                               const gchar* name,
                               const gchar* url);
VALA_EXTERN const gchar* repo_info_get_list (RepoInfo* self);
VALA_EXTERN gint utils_run (gchar** av,
                gint av_length1,
                gboolean silence,
                gchar** envp,
                gint envp_length1);
static void repo_info_finalize (RepoInfo * obj);
static GType repo_info_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

void
supra_list_init (SupraList *self,
                 const gchar* repo_name,
                 const gchar* line)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (repo_name != NULL);
	g_return_if_fail (line != NULL);
	memset (self, 0, sizeof (SupraList));
	(*self).repo_name = repo_name;
	_tmp0_ = g_strdup ("");
	_g_free0 ((*self).name);
	(*self).name = _tmp0_;
	_tmp1_ = g_strdup ("");
	_g_free0 ((*self).version);
	(*self).version = _tmp1_;
}

void
supra_list_copy (const SupraList* self,
                 SupraList* dest)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = (*self).repo_name;
	(*dest).repo_name = _tmp0_;
	_tmp1_ = (*self).name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp2_;
	_tmp3_ = (*self).version;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 ((*dest).version);
	(*dest).version = _tmp4_;
}

void
supra_list_destroy (SupraList* self)
{
	_g_free0 ((*self).name);
	_g_free0 ((*self).version);
}

SupraList*
supra_list_dup (const SupraList* self)
{
	SupraList* dup;
	dup = g_new0 (SupraList, 1);
	supra_list_copy (self, dup);
	return dup;
}

void
supra_list_free (SupraList* self)
{
	supra_list_destroy (self);
	g_free (self);
}

static GType
supra_list_get_type_once (void)
{
	GType supra_list_type_id;
	supra_list_type_id = g_boxed_type_register_static ("SupraList", (GBoxedCopyFunc) supra_list_dup, (GBoxedFreeFunc) supra_list_free);
	return supra_list_type_id;
}

GType
supra_list_get_type (void)
{
	static volatile gsize supra_list_type_id__once = 0;
	if (g_once_init_enter (&supra_list_type_id__once)) {
		GType supra_list_type_id;
		supra_list_type_id = supra_list_get_type_once ();
		g_once_init_leave (&supra_list_type_id__once, supra_list_type_id);
	}
	return supra_list_type_id__once;
}

static inline gpointer
repo_info_get_instance_private (RepoInfo* self)
{
	return G_STRUCT_MEMBER_P (self, RepoInfo_private_offset);
}

RepoInfo*
repo_info_construct (GType object_type,
                     const gchar* name,
                     const gchar* url)
{
	RepoInfo* self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (url != NULL, NULL);
	self = (RepoInfo*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (name);
	_g_free0 (self->name);
	self->name = _tmp0_;
	_tmp1_ = g_strdup (url);
	_g_free0 (self->url);
	self->url = _tmp1_;
	_g_free0 (self->priv->_list);
	self->priv->_list = NULL;
	return self;
}

RepoInfo*
repo_info_new (const gchar* name,
               const gchar* url)
{
	return repo_info_construct (TYPE_REPO_INFO, name, url);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

const gchar*
repo_info_get_list (RepoInfo* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	const gchar* _tmp20_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_list;
	if (_tmp0_ == NULL) {
		gchar* list_file = NULL;
		const gchar* _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar** av = NULL;
		gchar* _tmp6_;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		gchar* _tmp12_;
		gchar** _tmp13_;
		gint av_length1;
		gint _av_size_;
		gchar** _tmp14_;
		gint _tmp14__length1;
		gchar** _tmp15_;
		gchar** _tmp16_;
		gchar** _tmp17_;
		gint _tmp17__length1;
		const gchar* _tmp18_;
		gchar* _tmp19_;
		_tmp1_ = self->name;
		_tmp2_ = string_to_string (_tmp1_);
		_tmp3_ = USERNAME;
		_tmp4_ = string_to_string (_tmp3_);
		_tmp5_ = g_strconcat ("/tmp/", _tmp2_, "_", _tmp4_, "_list", NULL);
		list_file = _tmp5_;
		_tmp6_ = g_strdup ("curl");
		_tmp7_ = g_strdup ("-o");
		_tmp8_ = list_file;
		_tmp9_ = g_strdup (_tmp8_);
		_tmp10_ = self->url;
		_tmp11_ = string_to_string (_tmp10_);
		_tmp12_ = g_strconcat (_tmp11_, "/list", NULL);
		_tmp13_ = g_new0 (gchar*, 4 + 1);
		_tmp13_[0] = _tmp6_;
		_tmp13_[1] = _tmp7_;
		_tmp13_[2] = _tmp9_;
		_tmp13_[3] = _tmp12_;
		av = _tmp13_;
		av_length1 = 4;
		_av_size_ = av_length1;
		_tmp14_ = av;
		_tmp14__length1 = av_length1;
		_tmp16_ = _tmp15_ = g_get_environ ();
		_tmp17_ = _tmp16_;
		_tmp17__length1 = _vala_array_length (_tmp23_);
		utils_run (_tmp14_, (gint) _tmp14__length1, FALSE, _tmp17_, (gint) _vala_array_length (_tmp23_));
		_tmp17_ = (_vala_array_free (_tmp17_, _tmp17__length1, (GDestroyNotify) g_free), NULL);
		_tmp18_ = list_file;
		_tmp19_ = g_strdup (_tmp18_);
		_g_free0 (self->priv->_list);
		self->priv->_list = _tmp19_;
		av = (_vala_array_free (av, av_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (list_file);
	}
	_tmp20_ = self->priv->_list;
	result = _tmp20_;
	return result;
}

static void
value_repo_info_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_repo_info_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		repo_info_unref (value->data[0].v_pointer);
	}
}

static void
value_repo_info_copy_value (const GValue* src_value,
                            GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = repo_info_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_repo_info_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_repo_info_collect_value (GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		RepoInfo * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = repo_info_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_repo_info_lcopy_value (const GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	RepoInfo ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = repo_info_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_repo_info (const gchar* name,
                      const gchar* nick,
                      const gchar* blurb,
                      GType object_type,
                      GParamFlags flags)
{
	ParamSpecRepoInfo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_REPO_INFO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_repo_info (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO), NULL);
	return value->data[0].v_pointer;
}

void
value_set_repo_info (GValue* value,
                     gpointer v_object)
{
	RepoInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_REPO_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		repo_info_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		repo_info_unref (old);
	}
}

void
value_take_repo_info (GValue* value,
                      gpointer v_object)
{
	RepoInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_REPO_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		repo_info_unref (old);
	}
}

static void
repo_info_class_init (RepoInfoClass * klass,
                      gpointer klass_data)
{
	repo_info_parent_class = g_type_class_peek_parent (klass);
	((RepoInfoClass *) klass)->finalize = repo_info_finalize;
	g_type_class_adjust_private_offset (klass, &RepoInfo_private_offset);
}

static void
repo_info_instance_init (RepoInfo * self,
                         gpointer klass)
{
	self->priv = repo_info_get_instance_private (self);
	self->ref_count = 1;
}

static void
repo_info_finalize (RepoInfo * obj)
{
	RepoInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_REPO_INFO, RepoInfo);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->_list);
	_g_free0 (self->name);
	_g_free0 (self->url);
}

static GType
repo_info_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_repo_info_init, value_repo_info_free_value, value_repo_info_copy_value, value_repo_info_peek_pointer, "p", value_repo_info_collect_value, "p", value_repo_info_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (RepoInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repo_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RepoInfo), 0, (GInstanceInitFunc) repo_info_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType repo_info_type_id;
	repo_info_type_id = g_type_register_fundamental (g_type_fundamental_next (), "RepoInfo", &g_define_type_info, &g_define_type_fundamental_info, 0);
	RepoInfo_private_offset = g_type_add_instance_private (repo_info_type_id, sizeof (RepoInfoPrivate));
	return repo_info_type_id;
}

GType
repo_info_get_type (void)
{
	static volatile gsize repo_info_type_id__once = 0;
	if (g_once_init_enter (&repo_info_type_id__once)) {
		GType repo_info_type_id;
		repo_info_type_id = repo_info_get_type_once ();
		g_once_init_leave (&repo_info_type_id__once, repo_info_type_id);
	}
	return repo_info_type_id__once;
}

gpointer
repo_info_ref (gpointer instance)
{
	RepoInfo * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
repo_info_unref (gpointer instance)
{
	RepoInfo * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		REPO_INFO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

