/* Sync.c generated by valac 0.56.13, the Vala compiler
 * generated from Sync.vala, do not modify */

/*TODO read a file */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib-object.h>
#include <gobject/gvaluecollector.h>
#include <stdio.h>
#include <glib/gstdio.h>

#define REPO_URL "https://gitlab.com/supraproject/suprastore_repository/-/raw/master/"
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_SUPRA_LIST (supra_list_get_type ())
typedef struct _SupraList SupraList;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_REPO_INFO (repo_info_get_type ())
#define REPO_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REPO_INFO, RepoInfo))
#define REPO_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REPO_INFO, RepoInfoClass))
#define IS_REPO_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REPO_INFO))
#define IS_REPO_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REPO_INFO))
#define REPO_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REPO_INFO, RepoInfoClass))

typedef struct _RepoInfo RepoInfo;
typedef struct _RepoInfoClass RepoInfoClass;
typedef struct _RepoInfoPrivate RepoInfoPrivate;
typedef struct _ParamSpecRepoInfo ParamSpecRepoInfo;

#define TYPE_SYNC (sync_get_type ())
#define SYNC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SYNC, Sync))
#define SYNC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SYNC, SyncClass))
#define IS_SYNC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SYNC))
#define IS_SYNC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SYNC))
#define SYNC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SYNC, SyncClass))

typedef struct _Sync Sync;
typedef struct _SyncClass SyncClass;
typedef struct _SyncPrivate SyncPrivate;
#define _sync_unref0(var) ((var == NULL) ? NULL : (var = (sync_unref (var), NULL)))

#define TYPE_PACKAGE (package_get_type ())
typedef struct _Package Package;
#define _supra_list_free0(var) ((var == NULL) ? NULL : (var = (supra_list_free (var), NULL)))
#define _repo_info_unref0(var) ((var == NULL) ? NULL : (var = (repo_info_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
typedef struct _ParamSpecSync ParamSpecSync;

struct _SupraList {
	const gchar* repo_name;
	gchar* name;
	gchar* version;
};

struct _RepoInfo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RepoInfoPrivate * priv;
	gchar* name;
	gchar* url;
};

struct _RepoInfoClass {
	GTypeClass parent_class;
	void (*finalize) (RepoInfo *self);
};

struct _RepoInfoPrivate {
	gchar* _list;
};

struct _ParamSpecRepoInfo {
	GParamSpec parent_instance;
};

struct _Sync {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SyncPrivate * priv;
};

struct _SyncClass {
	GTypeClass parent_class;
	void (*finalize) (Sync *self);
};

struct _SyncPrivate {
	SupraList* _list;
	gint _list_length1;
	gint __list_size_;
	RepoInfo** _repo;
	gint _repo_length1;
	gint __repo_size_;
};

struct _Package {
	gchar* name;
	gchar* author;
	gchar* version;
	gchar* description;
	gchar* binary;
	gchar* dependency;
	gchar* installed_files;
};

struct _ParamSpecSync {
	GParamSpec parent_instance;
};

static gint RepoInfo_private_offset;
static gpointer repo_info_parent_class = NULL;
VALA_EXTERN gchar* USERNAME;
static gint Sync_private_offset;
static gpointer sync_parent_class = NULL;
static Sync* sync_singleton;
static Sync* sync_singleton = NULL;
VALA_EXTERN gchar* LOCAL;

VALA_EXTERN GType supra_list_get_type (void) G_GNUC_CONST ;
VALA_EXTERN SupraList* supra_list_dup (const SupraList* self);
VALA_EXTERN void supra_list_free (SupraList* self);
VALA_EXTERN void supra_list_copy (const SupraList* self,
                      SupraList* dest);
VALA_EXTERN void supra_list_destroy (SupraList* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (SupraList, supra_list_destroy)
VALA_EXTERN void supra_list_init (SupraList *self,
                      const gchar* repo_name,
                      const gchar* line);
VALA_EXTERN gpointer repo_info_ref (gpointer instance);
VALA_EXTERN void repo_info_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_repo_info (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
VALA_EXTERN void value_set_repo_info (GValue* value,
                          gpointer v_object);
VALA_EXTERN void value_take_repo_info (GValue* value,
                           gpointer v_object);
VALA_EXTERN gpointer value_get_repo_info (const GValue* value);
VALA_EXTERN GType repo_info_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (RepoInfo, repo_info_unref)
VALA_EXTERN RepoInfo* repo_info_new (const gchar* name,
                         const gchar* url);
VALA_EXTERN RepoInfo* repo_info_construct (GType object_type,
                               const gchar* name,
                               const gchar* url);
VALA_EXTERN const gchar* repo_info_get_list (RepoInfo* self);
VALA_EXTERN gint utils_run (gchar** av,
                gint av_length1,
                gboolean silence,
                gchar** envp,
                gint envp_length1);
static void repo_info_finalize (RepoInfo * obj);
static GType repo_info_get_type_once (void);
VALA_EXTERN gpointer sync_ref (gpointer instance);
VALA_EXTERN void sync_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_sync (const gchar* name,
                             const gchar* nick,
                             const gchar* blurb,
                             GType object_type,
                             GParamFlags flags);
VALA_EXTERN void value_set_sync (GValue* value,
                     gpointer v_object);
VALA_EXTERN void value_take_sync (GValue* value,
                      gpointer v_object);
VALA_EXTERN gpointer value_get_sync (const GValue* value);
VALA_EXTERN GType sync_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Sync, sync_unref)
static void _vala_SupraList_array_free (SupraList * array,
                                 gssize array_length);
VALA_EXTERN Sync* sync_default (void);
static Sync* sync_new (void);
static Sync* sync_construct (GType object_type);
static void _vala_array_add5 (RepoInfo** * array,
                       gint* length,
                       gint* size,
                       RepoInfo* value);
VALA_EXTERN SupraList* sync_get_from_pkg (const gchar* name_pkg);
VALA_EXTERN SupraList* sync_get_list_package (Sync* self,
                                  gint* result_length1);
VALA_EXTERN gboolean sync_check_update (const gchar* package_name);
VALA_EXTERN GType package_get_type (void) G_GNUC_CONST ;
VALA_EXTERN Package* package_dup (const Package* self);
VALA_EXTERN void package_free (Package* self);
VALA_EXTERN void package_copy (const Package* self,
                   Package* dest);
VALA_EXTERN void package_destroy (Package* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (Package, package_destroy)
VALA_EXTERN void query_get_from_pkg (const gchar* name_pkg,
                         Package* result);
static const gchar* sync_get_url_from_name (Sync* self,
                                     const gchar* repo_name);
VALA_EXTERN void print_error (const gchar* msg);
static void _vala_array_add6 (SupraList* * array,
                       gint* length,
                       gint* size,
                       const SupraList* value);
static SupraList* _vala_array_dup1 (SupraList* self,
                             gssize length);
VALA_EXTERN gchar* sync_download (Sync* self,
                      SupraList* pkg);
VALA_EXTERN gint utils_run_cmd (gchar** av,
                    gint av_length1);
static void sync_finalize (Sync * obj);
static GType sync_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);
static gssize _vala_array_length (gpointer array);

static gchar*
string_slice (const gchar* self,
              glong start,
              glong end)
{
	glong string_length = 0L;
	gint _tmp0_;
	gint _tmp1_;
	gboolean _tmp2_ = FALSE;
	gboolean _tmp3_ = FALSE;
	gchar* _tmp4_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	if (start < ((glong) 0)) {
		start = string_length + start;
	}
	if (end < ((glong) 0)) {
		end = string_length + end;
	}
	if (start >= ((glong) 0)) {
		_tmp2_ = start <= string_length;
	} else {
		_tmp2_ = FALSE;
	}
	g_return_val_if_fail (_tmp2_, NULL);
	if (end >= ((glong) 0)) {
		_tmp3_ = end <= string_length;
	} else {
		_tmp3_ = FALSE;
	}
	g_return_val_if_fail (_tmp3_, NULL);
	g_return_val_if_fail (start <= end, NULL);
	_tmp4_ = g_strndup (((gchar*) self) + start, (gsize) (end - start));
	result = _tmp4_;
	return result;
}

static gint
string_last_index_of_char (const gchar* self,
                           gunichar c,
                           gint start_index)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = g_utf8_strrchr (((gchar*) self) + start_index, (gssize) -1, c);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	if (_tmp1_ != NULL) {
		gchar* _tmp2_;
		_tmp2_ = _result_;
		result = (gint) (_tmp2_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}

void
supra_list_init (SupraList *self,
                 const gchar* repo_name,
                 const gchar* line)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (repo_name != NULL);
	g_return_if_fail (line != NULL);
	memset (self, 0, sizeof (SupraList));
	(*self).repo_name = repo_name;
	_tmp0_ = string_slice (line, (glong) 0, (glong) string_last_index_of_char (line, (gunichar) '-', 0));
	_g_free0 ((*self).name);
	(*self).name = _tmp0_;
	_tmp1_ = string_slice (line, (glong) (string_last_index_of_char (line, (gunichar) '-', 0) + 1), (glong) string_last_index_of_char (line, (gunichar) '.', 0));
	_g_free0 ((*self).version);
	(*self).version = _tmp1_;
}

void
supra_list_copy (const SupraList* self,
                 SupraList* dest)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	_tmp0_ = (*self).repo_name;
	(*dest).repo_name = _tmp0_;
	_tmp1_ = (*self).name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp2_;
	_tmp3_ = (*self).version;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 ((*dest).version);
	(*dest).version = _tmp4_;
}

void
supra_list_destroy (SupraList* self)
{
	_g_free0 ((*self).name);
	_g_free0 ((*self).version);
}

SupraList*
supra_list_dup (const SupraList* self)
{
	SupraList* dup;
	dup = g_new0 (SupraList, 1);
	supra_list_copy (self, dup);
	return dup;
}

void
supra_list_free (SupraList* self)
{
	supra_list_destroy (self);
	g_free (self);
}

static GType
supra_list_get_type_once (void)
{
	GType supra_list_type_id;
	supra_list_type_id = g_boxed_type_register_static ("SupraList", (GBoxedCopyFunc) supra_list_dup, (GBoxedFreeFunc) supra_list_free);
	return supra_list_type_id;
}

GType
supra_list_get_type (void)
{
	static volatile gsize supra_list_type_id__once = 0;
	if (g_once_init_enter (&supra_list_type_id__once)) {
		GType supra_list_type_id;
		supra_list_type_id = supra_list_get_type_once ();
		g_once_init_leave (&supra_list_type_id__once, supra_list_type_id);
	}
	return supra_list_type_id__once;
}

static inline gpointer
repo_info_get_instance_private (RepoInfo* self)
{
	return G_STRUCT_MEMBER_P (self, RepoInfo_private_offset);
}

RepoInfo*
repo_info_construct (GType object_type,
                     const gchar* name,
                     const gchar* url)
{
	RepoInfo* self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (url != NULL, NULL);
	self = (RepoInfo*) g_type_create_instance (object_type);
	_tmp0_ = g_strdup (name);
	_g_free0 (self->name);
	self->name = _tmp0_;
	_tmp1_ = g_strdup (url);
	_g_free0 (self->url);
	self->url = _tmp1_;
	_g_free0 (self->priv->_list);
	self->priv->_list = NULL;
	return self;
}

RepoInfo*
repo_info_new (const gchar* name,
               const gchar* url)
{
	return repo_info_construct (TYPE_REPO_INFO, name, url);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

const gchar*
repo_info_get_list (RepoInfo* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	const gchar* _tmp20_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_list;
	if (_tmp0_ == NULL) {
		gchar* list_file = NULL;
		const gchar* _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		gchar* _tmp5_;
		gchar** av = NULL;
		gchar* _tmp6_;
		gchar* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		gchar* _tmp12_;
		gchar** _tmp13_;
		gint av_length1;
		gint _av_size_;
		gchar** _tmp14_;
		gint _tmp14__length1;
		gchar** _tmp15_;
		gchar** _tmp16_;
		gchar** _tmp17_;
		gint _tmp17__length1;
		const gchar* _tmp18_;
		gchar* _tmp19_;
		_tmp1_ = self->name;
		_tmp2_ = string_to_string (_tmp1_);
		_tmp3_ = USERNAME;
		_tmp4_ = string_to_string (_tmp3_);
		_tmp5_ = g_strconcat ("/tmp/", _tmp2_, "_", _tmp4_, "_list", NULL);
		list_file = _tmp5_;
		_tmp6_ = g_strdup ("curl");
		_tmp7_ = g_strdup ("-o");
		_tmp8_ = list_file;
		_tmp9_ = g_strdup (_tmp8_);
		_tmp10_ = self->url;
		_tmp11_ = string_to_string (_tmp10_);
		_tmp12_ = g_strconcat (_tmp11_, "/list", NULL);
		_tmp13_ = g_new0 (gchar*, 4 + 1);
		_tmp13_[0] = _tmp6_;
		_tmp13_[1] = _tmp7_;
		_tmp13_[2] = _tmp9_;
		_tmp13_[3] = _tmp12_;
		av = _tmp13_;
		av_length1 = 4;
		_av_size_ = av_length1;
		_tmp14_ = av;
		_tmp14__length1 = av_length1;
		_tmp16_ = _tmp15_ = g_get_environ ();
		_tmp17_ = _tmp16_;
		_tmp17__length1 = _vala_array_length (_tmp38_);
		utils_run (_tmp14_, (gint) _tmp14__length1, FALSE, _tmp17_, (gint) _vala_array_length (_tmp38_));
		_tmp17_ = (_vala_array_free (_tmp17_, _tmp17__length1, (GDestroyNotify) g_free), NULL);
		_tmp18_ = list_file;
		_tmp19_ = g_strdup (_tmp18_);
		_g_free0 (self->priv->_list);
		self->priv->_list = _tmp19_;
		av = (_vala_array_free (av, av_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (list_file);
	}
	_tmp20_ = self->priv->_list;
	result = _tmp20_;
	return result;
}

static void
value_repo_info_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_repo_info_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		repo_info_unref (value->data[0].v_pointer);
	}
}

static void
value_repo_info_copy_value (const GValue* src_value,
                            GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = repo_info_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_repo_info_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_repo_info_collect_value (GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		RepoInfo * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = repo_info_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_repo_info_lcopy_value (const GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	RepoInfo ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = repo_info_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_repo_info (const gchar* name,
                      const gchar* nick,
                      const gchar* blurb,
                      GType object_type,
                      GParamFlags flags)
{
	ParamSpecRepoInfo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_REPO_INFO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_repo_info (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO), NULL);
	return value->data[0].v_pointer;
}

void
value_set_repo_info (GValue* value,
                     gpointer v_object)
{
	RepoInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_REPO_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		repo_info_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		repo_info_unref (old);
	}
}

void
value_take_repo_info (GValue* value,
                      gpointer v_object)
{
	RepoInfo * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_REPO_INFO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_REPO_INFO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		repo_info_unref (old);
	}
}

static void
repo_info_class_init (RepoInfoClass * klass,
                      gpointer klass_data)
{
	repo_info_parent_class = g_type_class_peek_parent (klass);
	((RepoInfoClass *) klass)->finalize = repo_info_finalize;
	g_type_class_adjust_private_offset (klass, &RepoInfo_private_offset);
}

static void
repo_info_instance_init (RepoInfo * self,
                         gpointer klass)
{
	self->priv = repo_info_get_instance_private (self);
	self->ref_count = 1;
}

static void
repo_info_finalize (RepoInfo * obj)
{
	RepoInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_REPO_INFO, RepoInfo);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->_list);
	_g_free0 (self->name);
	_g_free0 (self->url);
}

static GType
repo_info_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_repo_info_init, value_repo_info_free_value, value_repo_info_copy_value, value_repo_info_peek_pointer, "p", value_repo_info_collect_value, "p", value_repo_info_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (RepoInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repo_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RepoInfo), 0, (GInstanceInitFunc) repo_info_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType repo_info_type_id;
	repo_info_type_id = g_type_register_fundamental (g_type_fundamental_next (), "RepoInfo", &g_define_type_info, &g_define_type_fundamental_info, 0);
	RepoInfo_private_offset = g_type_add_instance_private (repo_info_type_id, sizeof (RepoInfoPrivate));
	return repo_info_type_id;
}

GType
repo_info_get_type (void)
{
	static volatile gsize repo_info_type_id__once = 0;
	if (g_once_init_enter (&repo_info_type_id__once)) {
		GType repo_info_type_id;
		repo_info_type_id = repo_info_get_type_once ();
		g_once_init_leave (&repo_info_type_id__once, repo_info_type_id);
	}
	return repo_info_type_id__once;
}

gpointer
repo_info_ref (gpointer instance)
{
	RepoInfo * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
repo_info_unref (gpointer instance)
{
	RepoInfo * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		REPO_INFO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static inline gpointer
sync_get_instance_private (Sync* self)
{
	return G_STRUCT_MEMBER_P (self, Sync_private_offset);
}

static void
_vala_SupraList_array_free (SupraList * array,
                            gssize array_length)
{
	if (array != NULL) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			supra_list_destroy (&array[i]);
		}
	}
	g_free (array);
}

Sync*
sync_default (void)
{
	Sync* _tmp0_;
	Sync* _tmp2_;
	Sync* result;
	_tmp0_ = sync_singleton;
	if (_tmp0_ == NULL) {
		Sync* _tmp1_;
		_tmp1_ = sync_new ();
		_sync_unref0 (sync_singleton);
		sync_singleton = _tmp1_;
	}
	_tmp2_ = sync_singleton;
	result = _tmp2_;
	return result;
}

static void
_vala_array_add5 (RepoInfo** * array,
                  gint* length,
                  gint* size,
                  RepoInfo* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (RepoInfo*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static Sync*
sync_construct (GType object_type)
{
	Sync* self = NULL;
	SupraList* _tmp0_;
	RepoInfo* _tmp1_;
	self = (Sync*) g_type_create_instance (object_type);
	_tmp0_ = g_new0 (SupraList, 0);
	self->priv->_list = (_vala_SupraList_array_free (self->priv->_list, self->priv->_list_length1), NULL);
	self->priv->_list = _tmp0_;
	self->priv->_list_length1 = 0;
	self->priv->__list_size_ = self->priv->_list_length1;
	_tmp1_ = repo_info_new ("Cosmos", REPO_URL);
	_vala_array_add5 (&self->priv->_repo, &self->priv->_repo_length1, &self->priv->__repo_size_, _tmp1_);
	return self;
}

static Sync*
sync_new (void)
{
	return sync_construct (TYPE_SYNC);
}

static gpointer
_supra_list_dup0 (gpointer self)
{
	return self ? supra_list_dup (self) : NULL;
}

SupraList*
sync_get_from_pkg (const gchar* name_pkg)
{
	SupraList* pkg_list = NULL;
	Sync* _tmp0_;
	gint _tmp1_ = 0;
	SupraList* _tmp2_;
	gint pkg_list_length1;
	gint _pkg_list_size_;
	SupraList* _tmp3_;
	gint _tmp3__length1;
	SupraList* result;
	g_return_val_if_fail (name_pkg != NULL, NULL);
	_tmp0_ = sync_default ();
	_tmp2_ = sync_get_list_package (_tmp0_, &_tmp1_);
	pkg_list = _tmp2_;
	pkg_list_length1 = _tmp1_;
	_pkg_list_size_ = pkg_list_length1;
	_tmp3_ = pkg_list;
	_tmp3__length1 = pkg_list_length1;
	{
		SupraList* pkg_collection = NULL;
		gint pkg_collection_length1 = 0;
		gint _pkg_collection_size_ = 0;
		gint pkg_it = 0;
		pkg_collection = _tmp3_;
		pkg_collection_length1 = _tmp3__length1;
		for (pkg_it = 0; pkg_it < pkg_collection_length1; pkg_it = pkg_it + 1) {
			SupraList _tmp4_;
			SupraList _tmp5_ = {0};
			SupraList pkg = {0};
			_tmp4_ = pkg_collection[pkg_it];
			supra_list_copy (&_tmp4_, &_tmp5_);
			pkg = _tmp5_;
			{
				SupraList _tmp6_;
				const gchar* _tmp7_;
				_tmp6_ = pkg;
				_tmp7_ = _tmp6_.name;
				if (g_strcmp0 (_tmp7_, name_pkg) == 0) {
					SupraList _tmp8_;
					SupraList* _tmp9_;
					SupraList* _tmp10_;
					_tmp8_ = pkg;
					_tmp9_ = _supra_list_dup0 (&_tmp8_);
					_tmp10_ = _tmp9_;
					supra_list_destroy (&_tmp8_);
					result = _tmp10_;
					pkg_list = (_vala_SupraList_array_free (pkg_list, pkg_list_length1), NULL);
					return result;
				}
				supra_list_destroy (&pkg);
			}
		}
	}
	result = NULL;
	pkg_list = (_vala_SupraList_array_free (pkg_list, pkg_list_length1), NULL);
	return result;
}

gboolean
sync_check_update (const gchar* package_name)
{
	Package Qpkg = {0};
	Package _tmp0_ = {0};
	SupraList* Spkg = NULL;
	SupraList* _tmp1_;
	SupraList* _tmp2_;
	SupraList* _tmp3_;
	const gchar* _tmp4_;
	Package _tmp5_;
	const gchar* _tmp6_;
	gboolean result;
	g_return_val_if_fail (package_name != NULL, FALSE);
	query_get_from_pkg (package_name, &_tmp0_);
	Qpkg = _tmp0_;
	_tmp1_ = sync_get_from_pkg (package_name);
	Spkg = _tmp1_;
	_tmp2_ = Spkg;
	if (_tmp2_ == NULL) {
		result = FALSE;
		_supra_list_free0 (Spkg);
		package_destroy (&Qpkg);
		return result;
	}
	_tmp3_ = Spkg;
	_tmp4_ = (*_tmp3_).version;
	_tmp5_ = Qpkg;
	_tmp6_ = _tmp5_.version;
	result = g_strcmp0 (_tmp4_, _tmp6_) != 0;
	_supra_list_free0 (Spkg);
	package_destroy (&Qpkg);
	return result;
}

static gpointer
_repo_info_ref0 (gpointer self)
{
	return self ? repo_info_ref (self) : NULL;
}

static const gchar*
sync_get_url_from_name (Sync* self,
                        const gchar* repo_name)
{
	RepoInfo** _tmp0_;
	gint _tmp0__length1;
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (repo_name != NULL, NULL);
	_tmp0_ = self->priv->_repo;
	_tmp0__length1 = self->priv->_repo_length1;
	{
		RepoInfo** repo_collection = NULL;
		gint repo_collection_length1 = 0;
		gint _repo_collection_size_ = 0;
		gint repo_it = 0;
		repo_collection = _tmp0_;
		repo_collection_length1 = _tmp0__length1;
		for (repo_it = 0; repo_it < repo_collection_length1; repo_it = repo_it + 1) {
			RepoInfo* _tmp1_;
			RepoInfo* repo = NULL;
			_tmp1_ = _repo_info_ref0 (repo_collection[repo_it]);
			repo = _tmp1_;
			{
				RepoInfo* _tmp2_;
				const gchar* _tmp3_;
				_tmp2_ = repo;
				_tmp3_ = _tmp2_->name;
				if (g_strcmp0 (_tmp3_, repo_name) == 0) {
					RepoInfo* _tmp4_;
					const gchar* _tmp5_;
					_tmp4_ = repo;
					_tmp5_ = _tmp4_->url;
					result = _tmp5_;
					_repo_info_unref0 (repo);
					return result;
				}
				_repo_info_unref0 (repo);
			}
		}
	}
	result = NULL;
	return result;
}

static gchar*
g_file_stream_read_line (FILE* self)
{
	gint c = 0;
	GString* ret = NULL;
	GString* _tmp3_;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	ret = NULL;
	while (TRUE) {
		GString* _tmp0_;
		GString* _tmp2_;
		c = fgetc (self);
		if (!(c != EOF)) {
			break;
		}
		_tmp0_ = ret;
		if (_tmp0_ == NULL) {
			GString* _tmp1_;
			_tmp1_ = g_string_new ("");
			_g_string_free0 (ret);
			ret = _tmp1_;
		}
		if (c == ((gint) '\n')) {
			break;
		}
		_tmp2_ = ret;
		g_string_append_c ((GString*) _tmp2_, (gchar) c);
	}
	_tmp3_ = ret;
	if (_tmp3_ == NULL) {
		result = NULL;
		_g_string_free0 (ret);
		return result;
	} else {
		GString* _tmp4_;
		const gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = ret;
		_tmp5_ = ((GString*) _tmp4_)->str;
		_tmp6_ = g_strdup (_tmp5_);
		result = _tmp6_;
		_g_string_free0 (ret);
		return result;
	}
}

static void
_vala_array_add6 (SupraList* * array,
                  gint* length,
                  gint* size,
                  const SupraList* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (SupraList, *array, *size);
	}
	(*array)[(*length)++] = *value;
}

static SupraList*
_vala_array_dup1 (SupraList* self,
                  gssize length)
{
	if (length > 0) {
		SupraList* result;
		gssize i;
		result = g_new0 (SupraList, length);
		for (i = 0; i < length; i++) {
			SupraList _tmp0_;
			SupraList _tmp1_ = {0};
			_tmp0_ = self[i];
			supra_list_copy (&_tmp0_, &_tmp1_);
			result[i] = _tmp1_;
		}
		return result;
	}
	return NULL;
}

SupraList*
sync_get_list_package (Sync* self,
                       gint* result_length1)
{
	SupraList* _tmp0_;
	gint _tmp0__length1;
	SupraList* _tmp15_;
	gint _tmp15__length1;
	SupraList* _tmp16_;
	gint _tmp16__length1;
	SupraList* _tmp17_;
	gint _tmp17__length1;
	SupraList* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_list;
	_tmp0__length1 = self->priv->_list_length1;
	if (_tmp0__length1 == 0) {
		RepoInfo** _tmp1_;
		gint _tmp1__length1;
		_tmp1_ = self->priv->_repo;
		_tmp1__length1 = self->priv->_repo_length1;
		{
			RepoInfo** repo_collection = NULL;
			gint repo_collection_length1 = 0;
			gint _repo_collection_size_ = 0;
			gint repo_it = 0;
			repo_collection = _tmp1_;
			repo_collection_length1 = _tmp1__length1;
			for (repo_it = 0; repo_it < repo_collection_length1; repo_it = repo_it + 1) {
				RepoInfo* _tmp2_;
				RepoInfo* repo = NULL;
				_tmp2_ = _repo_info_ref0 (repo_collection[repo_it]);
				repo = _tmp2_;
				{
					FILE* fs = NULL;
					RepoInfo* _tmp3_;
					const gchar* _tmp4_;
					const gchar* _tmp5_;
					FILE* _tmp6_;
					FILE* _tmp7_;
					gchar* tmp = NULL;
					_tmp3_ = repo;
					_tmp4_ = repo_info_get_list (_tmp3_);
					_tmp5_ = _tmp4_;
					_tmp6_ = g_fopen (_tmp5_, "r");
					fs = _tmp6_;
					_tmp7_ = fs;
					if (_tmp7_ == NULL) {
						print_error ("list introuvable ???");
					}
					while (TRUE) {
						FILE* _tmp8_;
						gchar* _tmp9_;
						const gchar* _tmp10_;
						RepoInfo* _tmp11_;
						const gchar* _tmp12_;
						const gchar* _tmp13_;
						SupraList _tmp14_ = {0};
						_tmp8_ = fs;
						_tmp9_ = g_file_stream_read_line (_tmp8_);
						_g_free0 (tmp);
						tmp = _tmp9_;
						_tmp10_ = tmp;
						if (!(_tmp10_ != NULL)) {
							break;
						}
						_tmp11_ = repo;
						_tmp12_ = _tmp11_->name;
						_tmp13_ = tmp;
						supra_list_init (&_tmp14_, _tmp12_, _tmp13_);
						_vala_array_add6 (&self->priv->_list, &self->priv->_list_length1, &self->priv->__list_size_, &_tmp14_);
					}
					_g_free0 (tmp);
					_fclose0 (fs);
					_repo_info_unref0 (repo);
				}
			}
		}
	}
	_tmp15_ = self->priv->_list;
	_tmp15__length1 = self->priv->_list_length1;
	_tmp16_ = (_tmp15_ != NULL) ? _vala_array_dup1 (_tmp15_, _tmp15__length1) : _tmp15_;
	_tmp16__length1 = _tmp15__length1;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = _tmp16__length1;
	if (result_length1) {
		*result_length1 = _tmp17__length1;
	}
	result = _tmp17_;
	return result;
}

gchar*
sync_download (Sync* self,
               SupraList* pkg)
{
	gchar* pkgdir = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* pkgname = NULL;
	SupraList _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	SupraList _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* output = NULL;
	const gchar* _tmp10_;
	SupraList _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
	SupraList _tmp14_;
	const gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* url = NULL;
	SupraList _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	gchar** _tmp26_;
	gchar** _tmp27_;
	gint _tmp27__length1;
	gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pkg != NULL, NULL);
	_tmp0_ = LOCAL;
	_tmp1_ = string_to_string (_tmp0_);
	_tmp2_ = g_strconcat (_tmp1_, "/pkg", NULL);
	pkgdir = _tmp2_;
	_tmp3_ = *pkg;
	_tmp4_ = _tmp3_.name;
	_tmp5_ = string_to_string (_tmp4_);
	_tmp6_ = *pkg;
	_tmp7_ = _tmp6_.version;
	_tmp8_ = string_to_string (_tmp7_);
	_tmp9_ = g_strconcat (_tmp5_, "-", _tmp8_, ".suprapack", NULL);
	pkgname = _tmp9_;
	_tmp10_ = string_to_string (pkgdir);
	_tmp11_ = *pkg;
	_tmp12_ = _tmp11_.name;
	_tmp13_ = string_to_string (_tmp12_);
	_tmp14_ = *pkg;
	_tmp15_ = _tmp14_.version;
	_tmp16_ = string_to_string (_tmp15_);
	_tmp17_ = g_strconcat (_tmp10_, "/", _tmp13_, "-", _tmp16_, ".suprapack", NULL);
	output = _tmp17_;
	g_mkdir_with_parents (pkgdir, 0755);
	_tmp18_ = *pkg;
	_tmp19_ = _tmp18_.repo_name;
	_tmp20_ = sync_get_url_from_name (self, _tmp19_);
	_tmp21_ = g_strconcat (_tmp20_, pkgname, NULL);
	url = _tmp21_;
	_tmp22_ = g_strdup ("curl");
	_tmp23_ = g_strdup ("-o");
	_tmp24_ = g_strdup (output);
	_tmp25_ = g_strdup (url);
	_tmp26_ = g_new0 (gchar*, 4 + 1);
	_tmp26_[0] = _tmp22_;
	_tmp26_[1] = _tmp23_;
	_tmp26_[2] = _tmp24_;
	_tmp26_[3] = _tmp25_;
	_tmp27_ = _tmp26_;
	_tmp27__length1 = 4;
	utils_run_cmd (_tmp27_, (gint) 4);
	_tmp27_ = (_vala_array_free (_tmp27_, _tmp27__length1, (GDestroyNotify) g_free), NULL);
	result = output;
	_g_free0 (url);
	_g_free0 (pkgname);
	_g_free0 (pkgdir);
	return result;
}

static void
value_sync_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_sync_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		sync_unref (value->data[0].v_pointer);
	}
}

static void
value_sync_copy_value (const GValue* src_value,
                       GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = sync_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_sync_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_sync_collect_value (GValue* value,
                          guint n_collect_values,
                          GTypeCValue* collect_values,
                          guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		Sync * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = sync_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_sync_lcopy_value (const GValue* value,
                        guint n_collect_values,
                        GTypeCValue* collect_values,
                        guint collect_flags)
{
	Sync ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = sync_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_sync (const gchar* name,
                 const gchar* nick,
                 const gchar* blurb,
                 GType object_type,
                 GParamFlags flags)
{
	ParamSpecSync* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_SYNC), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_sync (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SYNC), NULL);
	return value->data[0].v_pointer;
}

void
value_set_sync (GValue* value,
                gpointer v_object)
{
	Sync * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SYNC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_SYNC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		sync_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sync_unref (old);
	}
}

void
value_take_sync (GValue* value,
                 gpointer v_object)
{
	Sync * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_SYNC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_SYNC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sync_unref (old);
	}
}

static void
sync_class_init (SyncClass * klass,
                 gpointer klass_data)
{
	sync_parent_class = g_type_class_peek_parent (klass);
	((SyncClass *) klass)->finalize = sync_finalize;
	g_type_class_adjust_private_offset (klass, &Sync_private_offset);
}

static void
sync_instance_init (Sync * self,
                    gpointer klass)
{
	self->priv = sync_get_instance_private (self);
	self->ref_count = 1;
}

static void
sync_finalize (Sync * obj)
{
	Sync * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SYNC, Sync);
	g_signal_handlers_destroy (self);
	self->priv->_list = (_vala_SupraList_array_free (self->priv->_list, self->priv->_list_length1), NULL);
	self->priv->_repo = (_vala_array_free (self->priv->_repo, self->priv->_repo_length1, (GDestroyNotify) repo_info_unref), NULL);
}

static GType
sync_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { value_sync_init, value_sync_free_value, value_sync_copy_value, value_sync_peek_pointer, "p", value_sync_collect_value, "p", value_sync_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (SyncClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sync_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Sync), 0, (GInstanceInitFunc) sync_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType sync_type_id;
	sync_type_id = g_type_register_fundamental (g_type_fundamental_next (), "Sync", &g_define_type_info, &g_define_type_fundamental_info, 0);
	Sync_private_offset = g_type_add_instance_private (sync_type_id, sizeof (SyncPrivate));
	return sync_type_id;
}

GType
sync_get_type (void)
{
	static volatile gsize sync_type_id__once = 0;
	if (g_once_init_enter (&sync_type_id__once)) {
		GType sync_type_id;
		sync_type_id = sync_get_type_once ();
		g_once_init_leave (&sync_type_id__once, sync_type_id);
	}
	return sync_type_id__once;
}

gpointer
sync_ref (gpointer instance)
{
	Sync * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
sync_unref (gpointer instance)
{
	Sync * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SYNC_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gssize
_vala_array_length (gpointer array)
{
	gssize length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

